#!/bin/bash

# Treat unset variables as an error
set -u
#=================================================
# GENERIC STARTING
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================

app=$YNH_APP_INSTANCE_NAME

domain=$(ynh_app_setting_get $app domain)
db_name=$(ynh_app_setting_get $app db_name)
domain=$(ynh_app_setting_get "$app" domain)

#=================================================
# STANDARD REMOVE
#=================================================

#=================================================
# REMOVE APP MAIN DIR
#=================================================

ynh_secure_remove "/var/www/$app"

#=================================================
# REMOVE NGINX AND PHP-FPM CONFIGURATION
#=================================================
# Delete app directory and configurations
sudo ynh_secure_remove --file="/var/www/${app}"
sudo ynh_secure_remove --file="/etc/php5/fpm/pool.d/${app}.conf"
[[ -n $domain ]] && sudo ynh_secure_remove --file="/etc/nginx/conf.d/${domain}.d/${app}.conf"

# Reload services
sudo systemctl restart php5-fpm
sudo systemctl reload nginx

#=================================================
# REMOVE DEDICATED USER
#=================================================

ynh_system_user_delete $app
