#!/bin/bash

# Treat unset variables as an error
set -u
#=================================================
# GENERIC STARTING
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================

app=$YNH_APP_INSTANCE_NAME

domain=$(ynh_app_setting_get $app domain)
db_name=$(ynh_app_setting_get $app db_name)

#=================================================
# STANDARD REMOVE
#=================================================

#=================================================
# REMOVE APP MAIN DIR
#=================================================

ynh_secure_remove "/var/www/$app"

#=================================================
# REMOVE NGINX AND PHP-FPM CONFIGURATION
#=================================================

ynh_secure_remove --file="/etc/php5/fpm/pool.d/${app}.conf"
ynh_secure_remove --file="/etc/nginx/conf.d/${domain}.d/${app}.conf"

# Reload services
systemctl restart php5-fpm
systemctl reload nginx

#=================================================
# REMOVE DEDICATED USER
#=================================================

ynh_system_user_delete $app
